services:
  apache2:
    build: ${PWD}/apache2
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/apache2/etc/conf:/usr/local/apache2/conf
      - ${HOME}/Sites:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"
  fpm81:
    build: ${PWD}/php/8.1-fpm/
    restart: always
    volumes:
      - ${PWD}/php/8.1-fpm/etc/php-fpm.ini:/usr/local/etc/php/conf.d/zz-magento.ini
      - ${PWD}/php/8.1-fpm/etc/php-pcov.ini:/usr/local/etc/php/conf.d/zz-pcov-settings.ini
      - ${PWD}/php/8.1-fpm/etc/mail.ini:/usr/local/etc/php/conf.d/zz-mail.ini
      - ${PWD}/php/8.1-fpm/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ${PWD}/php/8.1-fpm/etc/php-gnupg.ini:/usr/local/etc/php/conf.d/gnupg.ini
      - ${PWD}/utils/m2install.sh:/usr/local/bin/m2install.sh
      - ${PWD}/utils/.m2install.conf:/var/www/.m2install.conf
      - ${PWD}/utils/.composer:/var/www/html/.composer
      - ${PWD}/utils/.cache/composer:/var/www/html/.cache/composer
      - ${HOME}/Sites:/var/www/html
    environment:
      MAGENTO_RUN_MODE: developer
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "php83.125.168.126.179.nip.io:host-gateway"
  fpm81-debug:
    build: ${PWD}/php/8.1-fpm/
    restart: always
    volumes:
      - ${PWD}/php/8.1-fpm/etc/php-fpm.ini:/usr/local/etc/php/conf.d/zz-magento.ini
      - ${PWD}/php/8.1-fpm/etc/php-xdebug.ini:/usr/local/etc/php/conf.d/zz-xdebug-settings.ini
      - ${PWD}/php/8.1-fpm/etc/php-pcov.ini:/usr/local/etc/php/conf.d/zz-pcov-settings.ini
      - ${PWD}/php/8.1-fpm/etc/mail.ini:/usr/local/etc/php/conf.d/zz-mail.ini
      - ${PWD}/php/8.1-fpm/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ${PWD}/php/8.1-fpm/etc/php-gnupg.ini:/usr/local/etc/php/conf.d/gnupg.ini
      - ${PWD}/utils/m2install.sh:/usr/local/bin/m2install.sh
      - ${PWD}/utils/.m2install.conf:/var/www/.m2install.conf
      - ${PWD}/utils/.composer:/var/www/html/.composer
      - ${PWD}/utils/.cache/composer:/var/www/html/.cache/composer
      - ${HOME}/Sites:/var/www/html
    environment:
      MAGENTO_RUN_MODE: developer
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "php83.125.168.126.179.nip.io:host-gateway"
  fpm82:
    build: ${PWD}/php/8.2-fpm/
    restart: always
    volumes:
      - ${PWD}/php/8.2-fpm/etc/php-fpm.ini:/usr/local/etc/php/conf.d/zz-magento.ini
      - ${PWD}/php/8.2-fpm/etc/php-pcov.ini:/usr/local/etc/php/conf.d/zz-pcov-settings.ini
      - ${PWD}/php/8.2-fpm/etc/mail.ini:/usr/local/etc/php/conf.d/zz-mail.ini
      - ${PWD}/php/8.2-fpm/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ${PWD}/php/8.2-fpm/etc/php-gnupg.ini:/usr/local/etc/php/conf.d/gnupg.ini
      - ${PWD}/utils/m2install.sh:/usr/local/bin/m2install.sh
      - ${PWD}/utils/.m2install.conf:/var/www/.m2install.conf
      - ${PWD}/utils/.composer:/var/www/html/.composer
      - ${PWD}/utils/.cache/composer:/var/www/html/.cache/composer
      - ${HOME}/Sites:/var/www/html
    environment:
      MAGENTO_RUN_MODE: developer
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "php83.125.168.126.179.nip.io:host-gateway"
  fpm82-debug:
    build: ${PWD}/php/8.2-fpm/
    restart: always
    volumes:
      - ${PWD}/php/8.2-fpm/etc/php-fpm.ini:/usr/local/etc/php/conf.d/zz-magento.ini
      - ${PWD}/php/8.2-fpm/etc/php-xdebug.ini:/usr/local/etc/php/conf.d/zz-xdebug-settings.ini
      - ${PWD}/php/8.2-fpm/etc/php-pcov.ini:/usr/local/etc/php/conf.d/zz-pcov-settings.ini
      - ${PWD}/php/8.2-fpm/etc/mail.ini:/usr/local/etc/php/conf.d/zz-mail.ini
      - ${PWD}/php/8.2-fpm/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ${PWD}/php/8.2-fpm/etc/php-gnupg.ini:/usr/local/etc/php/conf.d/gnupg.ini
      - ${PWD}/utils/m2install.sh:/usr/local/bin/m2install.sh
      - ${PWD}/utils/.m2install.conf:/var/www/.m2install.conf
      - ${PWD}/utils/.composer:/var/www/html/.composer
      - ${PWD}/utils/.cache/composer:/var/www/html/.cache/composer
      - ${HOME}/Sites:/var/www/html
    environment:
      MAGENTO_RUN_MODE: developer
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "php83.125.168.126.179.nip.io:host-gateway"
  fpm83:
    build: ${PWD}/php/8.3-fpm/
    restart: always
    volumes:
      - ${PWD}/php/8.3-fpm/etc/php-fpm.ini:/usr/local/etc/php/conf.d/zz-magento.ini
      - ${PWD}/php/8.3-fpm/etc/php-pcov.ini:/usr/local/etc/php/conf.d/zz-pcov-settings.ini
      - ${PWD}/php/8.3-fpm/etc/mail.ini:/usr/local/etc/php/conf.d/zz-mail.ini
      - ${PWD}/php/8.3-fpm/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ${PWD}/php/8.3-fpm/etc/php-gnupg.ini:/usr/local/etc/php/conf.d/gnupg.ini
      - ${PWD}/utils/m2install.sh:/usr/local/bin/m2install.sh
      - ${PWD}/utils/.m2install.conf:/var/www/.m2install.conf
      - ${PWD}/utils/.composer:/var/www/html/.composer
      - ${PWD}/utils/.cache/composer:/var/www/html/.cache/composer
      - ${HOME}/Sites:/var/www/html
    environment:
      MAGENTO_RUN_MODE: developer
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "php83.125.168.126.179.nip.io:host-gateway"
  fpm83-debug:
    build: ${PWD}/php/8.3-fpm/
    restart: always
    volumes:
      - ${PWD}/php/8.3-fpm/etc/php-fpm.ini:/usr/local/etc/php/conf.d/zz-magento.ini
      - ${PWD}/php/8.3-fpm/etc/php-xdebug-enabled.ini:/usr/local/etc/php/conf.d/zz-xdebug-settings.ini
      - ${PWD}/php/8.3-fpm/etc/php-pcov.ini:/usr/local/etc/php/conf.d/zz-pcov-settings.ini
      - ${PWD}/php/8.3-fpm/etc/mail.ini:/usr/local/etc/php/conf.d/zz-mail.ini
      - ${PWD}/php/8.3-fpm/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ${PWD}/php/8.3-fpm/etc/php-gnupg.ini:/usr/local/etc/php/conf.d/gnupg.ini
      - ${PWD}/utils/m2install.sh:/usr/local/bin/m2install.sh
      - ${PWD}/utils/.m2install.conf:/var/www/.m2install.conf
      - ${PWD}/utils/.composer:/var/www/html/.composer
      - ${PWD}/utils/.cache/composer:/var/www/html/.cache/composer
      - ${HOME}/Sites:/var/www/html
    environment:
      MAGENTO_RUN_MODE: developer
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "php83.125.168.126.179.nip.io:host-gateway"
  mariadb:
    image: mariadb:10.2
    restart: always
    volumes:
      - ${PWD}/mariadb/var/lib/mysql:/var/lib/mysql
      - ${PWD}/mariadb/etc/mysql:/etc/mysql
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
  opensearch:
    build: ${PWD}/opensearch
    restart: always
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m  # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    # ports:
    #   - "9200:9200"
  elasticsearch:
    build: ${PWD}/elasticsearch/7.11
    restart: always
    volumes:
    - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    # ports:
    #   - "9200:9200"
  rabbitmq:
    hostname: 'rabbitmq'
    image: rabbitmq:3.13.7-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
volumes:
  opensearch_data:
  elasticsearch_data:
  rabbitmq_data: