HTTP_HOST=https://local.test/
#HTTP_HOST=https://$(basename "$(pwd)").local.test/
#BASE_PATH=
BASE_PATH=$CURRENT_DIR_NAME
DB_HOST=mariadb
DB_USER=root
DB_PASSWORD=
MAGENTO_VERSION=2.3.3
# INSTALL_EE=1
INSTALL_B2B=
# GIT_CE_REPO=git@github.com:magento-sparta/magento2ce.git
GIT_CE_REPO=/Users/kavingas/Git/magento2ce-t4.git
# GIT_CE_REPO=/Users/kavingas/Git/l3-magento2ce.git
# GIT_EE_REPO=git@github.com:magento-sparta/magento2ee.git
GIT_EE_REPO=/Users/kavingas/Git/magento2ee-t4.git
# GIT_EE_REPO=/Users/kavingas/Git/l3-magento2ee.git
# GIT_B2B_REPO=git@github.com:magento-sparta/magento2b2b.git
GIT_B2B_REPO=/Users/kavingas/Git/magento2b2b-t4.git
MAGE_MODE=dev
BACKEND_FRONTNAME=admin
ADMIN_NAME=admin
ADMIN_PASSWORD=123123q
ADMIN_FIRSTNAME=Admin
ADMIN_LASTNAME=Test
ADMIN_EMAIL=admin@test.com
TIMEZONE=America/Chicago
LANGUAGE=en_US
CURRENCY=USD
CONFIG_GIT_WORKTREE_CE_PATH=/Users/kavingas/Sites/repo
CONFIG_GIT_WORKTREE_EE_PATH=/Users/kavingas/Sites/repo/magento2ee
REMOTE_DB_HOST=sparta-db:3306
REMOTE_HOST=kavingas@web2.sparta.corp.magento.com
REMOTE_KEY=/Users/kavingas/.ssh/id_rsa
LOCAL_PORT=62023
DB_NAME=$(basename "$(pwd)"|tr '-' '_')
BIN_COMPOSER=$(command -v composer)
BIN_MYSQL="mysql --init-command='SET SESSION FOREIGN_KEY_CHECKS=0;SET UNIQUE_CHECKS=0;'"
ELASTICSEARCH_HOST=127.0.0.1
ELASTICSEARCH_PORT=9200%