DirectoryIndex index.php index.html
# Enable http authorization headers
# This is required due to differences between how CGI and PHP expect to receive these headers
SetEnvIfNoCase ^Authorization$ "(.+)" HTTP_AUTHORIZATION=$1

# <FilesMatch \.php$>
# If you are using a TCP port, use the following format
# replacing the IP and port as needed:
# SetHandler "proxy:fcgi://fpm82:9000"

# If you are using a Unix socket, use the following format,
# rewriting the path to the socket to match your php-fpm configuration
# SetHandler "proxy:unix:/run/php-fpm/www.sock|fcgi://localhost"
# </FilesMatch>