LoadModule dispatcher_module modules/mod_dispatcher.so

<IfModule dispatcher_module>
    # Configuration for dispatcher module
    DispatcherConfig /usr/local/apache2/conf/dispatcher.any
    DispatcherLog    /proc/self/fd/1
    DispatcherLogLevel 3
    DispatcherNoServerHeader Off
    DispatcherDeclineRoot Off
    DispatcherUseProcessedURL Off
</IfModule>

<VirtualHost *:443>
    ServerName aem.125.168.126.179.nip.io:443
    DocumentRoot "/var/www/html/aem"
    ServerAdmin you@example.com
    ErrorLog /proc/self/fd/2
    TransferLog /proc/self/fd/1

    SSLEngine on
    SSLProtocol all -SSLv3 -TLSv1 -TLSv1.1
    SSLCipherSuite HIGH:!aNULL:!MD5

    # Security Headers
    #Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
    #Header always set X-Content-Type-Options "nosniff"
    #Header always set X-Frame-Options "DENY"
    #Header always set X-XSS-Protection "1; mode=block"

    
    SSLCertificateFile "/usr/local/apache2/conf/aem.crt"
    SSLCertificateKeyFile "/usr/local/apache2/conf/aem.key"

    # AEM Dispatcher
<Directory /var/www/html/aem>
    AllowOverride None
    Options FollowSymLinks
    Require all granted
    <IfModule disp_apache2.c>
     ModMimeUsePathInfo On
     SetHandler dispatcher-handler
  </IfModule>
</Directory>

BrowserMatch "MSIE [2-5]" \
                nokeepalive ssl-unclean-shutdown \
                downgrade-1.0 force-response-1.0

CustomLog /proc/self/fd/1 \
            "%t %h %{SSL_PROTOCOL}x %{SSL_CIPHER}x \"%r\" %b"

</VirtualHost>
