-- Create users with empty password for local development
CREATE USER IF NOT EXISTS 'kavingas'@'%' IDENTIFIED BY '';
GRANT ALL PRIVILEGES ON *.* TO 'kavingas'@'%' WITH GRANT OPTION;

CREATE USER IF NOT EXISTS 'root'@'%' IDENTIFIED BY '';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;

CREATE USER IF NOT EXISTS ''@'%' IDENTIFIED BY '';
GRANT ALL PRIVILEGES ON *.* TO ''@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;

