worker_processes auto;

error_log /var/log/nginx/error.log debug;
pid /var/run/nginx.pid;

events {
  # this should be equal to value of "ulimit -n"
  # reference: https://www.digitalocean.com/community/tutorials/how-to-optimize-nginx-configuration
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  map $uri $app_name {
        default default;
        ~^/([^/]+)/ $1;
  }
  map $app_name $doc_root {
        default /var/www/html;
        m247 /var/www/m247;  # Document root for "m247"
        # Add more mappings as needed
  }

  log_format main
    '$remote_addr - $remote_user [$time_local] "$request" '
    '$status $body_bytes_sent "$http_referer" '
    '"$http_user_agent" "$http_x_forwarded_for"';

  access_log /var/log/nginx/access.log main;

  sendfile on;
  #tcp_nopush on;

  keepalive_timeout 65;

  #gzip on;

  client_max_body_size 20M;

  #include_xdebug_upstream /etc/nginx/conf.d/xdebug/upstream.conf;
  include /etc/nginx/conf.d/*.conf;
}
