services:
  # Elasticsearch 7.11.2
  elasticsearch:
    build: ./elasticsearch
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      cluster.routing.allocation.disk.threshold_enabled: "false"
    restart: unless-stopped
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - search-network

  # # OpenSearch 1.2.4
  # opensearch_124:
  #   build: ./opensearch/1.2.4
  #   restart: unless-stopped
  #   environment:
  #     - discovery.type=single-node
  #     - cluster.routing.allocation.disk.threshold_enabled=false
  #     - DISABLE_INSTALL_DEMO_CONFIG=true
  #     - DISABLE_SECURITY_PLUGIN=true
  #     - ES_JAVA_OPTS="-Xms2g -Xmx2g"
  #   ports:
  #     - "9200:9200"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - opensearch-124-data:/usr/share/opensearch/data
  #   networks:
  #     - search-network

  # OpenSearch 2.12.0
  # opensearch_2120:
  #   image: opensearchproject/opensearch:2.12.0
  #   restart: unless-stopped
  #   environment:
  #     - discovery.type=single-node
  #     - bootstrap.memory_lock=true
  #     - OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g
  #     - cluster.routing.allocation.disk.threshold_enabled=false
  #     - DISABLE_INSTALL_DEMO_CONFIG=true
  #     - DISABLE_SECURITY_PLUGIN=true
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - opensearch-2120-data:/usr/share/opensearch/data
  #     - ./opensearch/2.12.0/config/opensearch.yml:/usr/share/opensearch/config/opensearch.yml
  #   ports:
  #     - "9202:9200"
  #     - "9601:9600"
  #   networks:
  #     - search-network

  # Elasticsearch Dashboard (Kibana 7.11.2)
  # elasticsearch_dashboard:
  #   image: docker.elastic.co/kibana/kibana:7.11.2
  #   platform: linux/amd64
  #   restart: unless-stopped
  #   ports:
  #     - "5602:5601"
  #   environment:
  #     ELASTICSEARCH_HOSTS: 'http://elasticsearch:9200'
  #   volumes:
  #     - elasticsearch-dashboard-data:/usr/share/kibana/data
  #   depends_on:
  #     - elasticsearch
  #   networks:
  #     - search-network

  # # OpenSearch Dashboard 1.2.4
  # opensearch_dashboard_124:
  #   image: opensearchproject/opensearch-dashboards:1.2.0
  #   restart: unless-stopped
  #   ports:
  #     - "5603:5601"
  #   environment:
  #     OPENSEARCH_HOSTS: 'http://opensearch_124:9200'
  #     DISABLE_SECURITY_DASHBOARDS_PLUGIN: 'true'
  #   volumes:
  #     - opensearch-dashboard-124-data:/usr/share/opensearch-dashboards/data
  #   depends_on:
  #     - opensearch_124
  #   networks:
  #     - search-network

  # # OpenSearch Dashboard 2.12.0
  # opensearch_dashboard_2120:
  #   image: opensearchproject/opensearch-dashboards:2.12.0
  #   restart: unless-stopped
  #   ports:
  #     - "5601:5601"
  #   environment:
  #     OPENSEARCH_HOSTS: 'http://opensearch_2120:9200'
  #     DISABLE_SECURITY_DASHBOARDS_PLUGIN: 'true'
  #   volumes:
  #     - opensearch-dashboard-2120-data:/usr/share/opensearch-dashboards/data
  #   depends_on:
  #     - opensearch_2120
  #   networks:
  #     - search-network

  mariadb102:
    image: mariadb:10.2
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - mariadb102-data:/var/lib/mysql
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mariadb/my.cnf:/etc/mysql/my.cnf
    networks:
      - search-network

  # mariadb:
  #   image: mariadb:10.6
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  #   ports:
  #     - "3308:3306"
  #   volumes:
  #     - mariadb-data:/var/lib/mysql
  #     - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
  #     - ./mariadb/my.cnf:/etc/mysql/my.cnf
  #   networks:
  #     - search-network
  
  # mariadb114:
  #   image: mariadb:11.4
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  #   ports:
  #     - "3309:3306"
  #   volumes:
  #     - mariadb114-data:/var/lib/mysql
  #     - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
  #     - ./mariadb/my.cnf:/etc/mysql/my.cnf
  #   networks:
  #     - search-network
  
  # mysql80:
  #   image: mysql:8.0
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  #   ports:
  #     - "3310:3306"
  #   volumes:
  #     - mysql80-data:/var/lib/mysql
  #     # - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
  #     - ./mariadb/my.cnf:/etc/mysql/my.cnf
  #   networks:
  #     - search-network

  rabbitmq:
    hostname: 'rabbitmq'
    image: rabbitmq:3.13.7-management-alpine
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq3_data:/var/lib/rabbitmq

  rabbitmq41:
    hostname: 'rabbitmq'
    image: rabbitmq:4.1.4-management-alpine
    restart: unless-stopped
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - rabbitmq4_data:/var/lib/rabbitmq
  
  valkey:
    image: valkey/valkey:8.0.1
    container_name: valkey-8.0.1
    ports:
      - "6370:6379"
    volumes:
      - ./valkey/data:/data
    command: >
      valkey-server
    restart: unless-stopped
    
networks:
  search-network:
    driver: bridge

volumes:
  elasticsearch-data:
  opensearch-124-data:
  opensearch-2120-data:
  elasticsearch-dashboard-data:
  opensearch-dashboard-124-data:
  opensearch-dashboard-2120-data:
  mariadb-data:
  mariadb102-data:
  mariadb114-data:
  # mysql80-data:
  rabbitmq3_data:
  rabbitmq4_data:
